name: add_activities_to_db

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
 run:
  working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        run: python scrape.py